{-# LANGUAGE OverloadedStrings #-}

module Test.Golden.Sophie.Key.ConvertBccAddressKey
  ( golden_convertBccAddressColeSigningKey
  , golden_convertBccAddressIcarusSigningKey
  , golden_convertBccAddressSophiePaymentSigningKey
  , golden_convertBccAddressSophieStakeSigningKey
  ) where

import           Bcc.Prelude hiding (readFile)
import           Hedgehog (Property, (===))
import           Test.OptParse

import qualified Hedgehog.Extras.Test.Base as H
import qualified Hedgehog.Extras.Test.File as H

{- HLINT ignore "Use camelCase" -}

-- | An example signing key generated by @bcc-address@ using the
-- deprecated Cole style.
exampleColeSigningKey :: Text
exampleColeSigningKey =
  "xprv1pp72a64en2vf568jywe9azlgrqe3p2jjf9gxxeejn2fex8g889x54w6emg2egkaz2rxyc"
    <> "560fp0hrv8y0hzpuzu27zhhhgwc8t5tvrczz2jnhhjwdnd6cdjx4dxehrsr2pr406rchw"
    <> "ctfwrgpc9r7nmakvaegyz9"

-- | An example signing key generated by @bcc-address@ using the Icarus
-- style.
exampleIcarusSigningKey :: Text
exampleIcarusSigningKey =
  "xprv1yq7c6nlmxncg7txy0z6lqf3fww4vm20m60lrxttx5lr4qmkvh395m3p59v8fn4ku9mzyc"
    <> "g2rkxatgwm86uc3pvrt06e43afya6rm0s2azlpnc9yrhygl2heckeyhhtgad08c0zljpn"
    <> "c6fse2ldzyx9c86yvddxjw"

-- | An example signing key generated by @bcc-address@ using the Sophie
-- style.
exampleSophieSigningKey :: Text
exampleSophieSigningKey =
  "xprv1yq7c6nlmxncg7txy0z6lqf3fww4vm20m60lrxttx5lr4qmkvh395m3p59v8fn4ku9mzyc"
    <> "g2rkxatgwm86uc3pvrt06e43afya6rm0s2azlpnc9yrhygl2heckeyhhtgad08c0zljpn"
    <> "c6fse2ldzyx9c86yvddxjw"

-- | Test that converting a @bcc-address@ Cole signing key yields the
-- expected result.
golden_convertBccAddressColeSigningKey :: Property
golden_convertBccAddressColeSigningKey =
  propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do

    -- `bcc-address` signing key filepath
    signingKeyFp <- noteTempFile tempDir "bcc-address-cole.skey"

    -- Converted signing key filepath
    convertedSigningKeyFp <-
      noteTempFile tempDir "converted-bcc-address-cole.skey"

    -- Write `bcc-address` signing key to disk
    H.textWriteFile signingKeyFp exampleColeSigningKey
    H.assertFilesExist [signingKeyFp]

    -- Convert the `bcc-address` signing key
    void $ execBccCLI
      [ "key","convert-bcc-address-key"
      , "--cole-payment-key"
      , "--signing-key-file", signingKeyFp
      , "--out-file", convertedSigningKeyFp
      ]

    -- Check for existence of the converted signing key file
    H.assertFilesExist [convertedSigningKeyFp]

    -- Check that the contents of the converted signing key file match that of
    -- the golden file.
    actualConvertedSigningKey <- H.readFile convertedSigningKeyFp
    expectedConvertedSigningKey <-
      H.readFile $
        "test/data/golden/sophie/keys/converted_bcc-address_keys/"
          <> "cole_signing_key"
    expectedConvertedSigningKey === actualConvertedSigningKey

-- | Test that converting a @bcc-address@ Icarus signing key yields the
-- expected result.
golden_convertBccAddressIcarusSigningKey :: Property
golden_convertBccAddressIcarusSigningKey =
  propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do

    -- `bcc-address` signing key filepath
    signingKeyFp <- H.noteTempFile tempDir "bcc-address-icarus.skey"

    -- Converted signing key filepath
    convertedSigningKeyFp <-
      noteTempFile tempDir "converted-bcc-address-icarus.skey"

    -- Write `bcc-address` signing key to disk
    H.textWriteFile signingKeyFp exampleIcarusSigningKey
    H.assertFilesExist [signingKeyFp]

    -- Convert the `bcc-address` signing key
    void $ execBccCLI
      [ "key","convert-bcc-address-key"
      , "--icarus-payment-key"
      , "--signing-key-file", signingKeyFp
      , "--out-file", convertedSigningKeyFp
      ]

    -- Check for existence of the converted signing key file
    H.assertFilesExist [convertedSigningKeyFp]

    -- Check that the contents of the converted signing key file match that of
    -- the golden file.
    actualConvertedSigningKey <- H.readFile convertedSigningKeyFp
    expectedConvertedSigningKey <-
      H.readFile $
        "test/data/golden/sophie/keys/converted_bcc-address_keys/"
          <> "icarus_signing_key"
    expectedConvertedSigningKey === actualConvertedSigningKey

-- | Test that converting a @bcc-address@ Sophie payment signing key
-- yields the expected result.
golden_convertBccAddressSophiePaymentSigningKey :: Property
golden_convertBccAddressSophiePaymentSigningKey =
  propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do

    -- `bcc-address` signing key filepath
    signingKeyFp <-
      noteTempFile tempDir "bcc-address-sophie-payment.skey"

    -- Converted signing key filepath
    convertedSigningKeyFp <-
      noteTempFile tempDir "converted-bcc-address-sophie-payment.skey"

    -- Write `bcc-address` signing key to disk
    H.textWriteFile signingKeyFp exampleSophieSigningKey
    H.assertFilesExist [signingKeyFp]

    -- Convert the `bcc-address` signing key
    void $ execBccCLI
      [ "key","convert-bcc-address-key"
      , "--sophie-payment-key"
      , "--signing-key-file", signingKeyFp
      , "--out-file", convertedSigningKeyFp
      ]

    -- Check for existence of the converted signing key file
    H.assertFilesExist [convertedSigningKeyFp]

    -- Check that the contents of the converted signing key file match that of
    -- the golden file.
    actualConvertedSigningKey <- H.readFile convertedSigningKeyFp
    expectedConvertedSigningKey <-
      H.readFile $
        "test/data/golden/sophie/keys/converted_bcc-address_keys/"
          <> "sophie_payment_signing_key"
    expectedConvertedSigningKey === actualConvertedSigningKey

-- | Test that converting a @bcc-address@ Sophie stake signing key yields
-- the expected result.
golden_convertBccAddressSophieStakeSigningKey :: Property
golden_convertBccAddressSophieStakeSigningKey =
  propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do

    -- `bcc-address` signing key filepath
    signingKeyFp <-
      noteTempFile tempDir "bcc-address-sophie-stake.skey"

    -- Converted signing key filepath
    convertedSigningKeyFp <-
      H.noteTempFile tempDir "converted-bcc-address-sophie-stake.skey"

    -- Write `bcc-address` signing key to disk
    H.textWriteFile signingKeyFp exampleSophieSigningKey
    H.assertFilesExist [signingKeyFp]

    -- Convert the `bcc-address` signing key
    void $ execBccCLI
      [ "key","convert-bcc-address-key"
      , "--sophie-stake-key"
      , "--signing-key-file", signingKeyFp
      , "--out-file", convertedSigningKeyFp
      ]

    -- Check for existence of the converted signing key file
    H.assertFilesExist [convertedSigningKeyFp]

    -- Check that the contents of the converted signing key file match that of
    -- the golden file.
    actualConvertedSigningKey <- H.readFile convertedSigningKeyFp
    expectedConvertedSigningKey <-
      H.readFile $
        "test/data/golden/sophie/keys/converted_bcc-address_keys/"
          <> "sophie_stake_signing_key"
    expectedConvertedSigningKey === actualConvertedSigningKey
