version: "3.5"

services:
  bcc-node:
    image: tbco/bcc-node:${BCC_NODE_VERSION:-1.99.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bcc-submit-api:
    image: tbco/bcc-submit-api:${BCC_SUBMIT_API_VERSION:-1.99.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    depends_on:
      - bcc-node
    volumes:
      - node-ipc:/node-ipc
    ports:
      - 8090:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc: