{
  "AurumGenesisFile": "aurum-genesis.json",
  "AurumGenesisHash": "06cc024b823b6d20f5dde2faf8de2d895f47983ab584db38ea62111b61038e35",
  "ApplicationName": "bcc-sl",
  "ApplicationVersion": 0,
  "ColeGenesisFile": "cole-genesis.json",
  "ColeGenesisHash": "954fd1fc35329395ae5ec031d5bd4621d6293d82b922a88132ec1d20c0d648f9",
  "LastKnownBlockVersion-Major": 5,
  "LastKnownBlockVersion-Sentry": 1,
  "MaxKnownMajorProtocolVersion": 2,
  "PBftSignatureThreshold": 1.1,
  "Protocol": "Bcc",
  "RequiresNetworkMagic": "RequiresMagic",
  "SophieGenesisFile": "sophie-genesis.json",
  "SophieGenesisHash": "60ba98183b381c933acaa298a815e090bdb86726fd19562e12f6ed6aa78caef2",
  "TestEvieHardForkAtEpoch": 2,
  "TestEnableDevelopmentHardForkEras": true,
  "TestEnableDevelopmentNetworkProtocols": true,
  "TestJenHardForkAtEpoch": 3,
  "TestSophieHardForkAtEpoch": 1,
  "TraceBlockFetchClient": false,
  "TraceBlockFetchDecisions": false,
  "TraceBlockFetchProtocol": false,
  "TraceBlockFetchProtocolSerialised": false,
  "TraceBlockFetchServer": false,
  "TraceChainDb": true,
  "TraceChainSyncBlockServer": false,
  "TraceChainSyncClient": false,
  "TraceChainSyncHeaderServer": false,
  "TraceChainSyncProtocol": false,
  "TraceConnectionManager": true,
  "TraceDNSResolver": true,
  "TraceDNSSubscription": true,
  "TraceDiffusionInitialization": true,
  "TraceErrorPolicy": true,
  "TraceForge": true,
  "TraceHandshake": false,
  "TraceInboundGovernor": true,
  "TraceIpSubscription": true,
  "TraceLedgerPeers": true,
  "TraceLocalChainSyncProtocol": false,
  "TraceLocalErrorPolicy": true,
  "TraceLocalHandshake": false,
  "TraceLocalRootPeers": true,
  "TraceLocalTxSubmissionProtocol": false,
  "TraceLocalTxSubmissionServer": false,
  "TraceMempool": true,
  "TraceMux": false,
  "TracePeerSelection": true,
  "TracePeerSelectionActions": true,
  "TracePublicRootPeers": true,
  "TraceServer": true,
  "TraceTxInbound": false,
  "TraceTxOutbound": false,
  "TraceTxSubmissionProtocol": false,
  "TracingVerbosity": "NormalVerbosity",
  "TurnOnLogMetrics": true,
  "TurnOnLogging": true,
  "defaultBackends": [
    "KatipBK"
  ],
  "defaultScribes": [
    [
      "StdoutSK",
      "stdout"
    ]
  ],
  "hasEKG": 12788,
  "hasPrometheus": [
    "127.0.0.1",
    12798
  ],
  "minSeverity": "Debug",
  "options": {
    "mapBackends": {
      "bcc.node.metrics": [
        "EKGViewBK"
      ],
      "bcc.node.resources": [
        "EKGViewBK"
      ]
    },
    "mapSubtrace": {
      "bcc.node.metrics": {
        "subtrace": "Neutral"
      }
    }
  },
  "rotation": {
    "rpKeepFilesNum": 10,
    "rpLogLimitBytes": 5000000,
    "rpMaxAgeHours": 24
  },
  "setupBackends": [
    "KatipBK"
  ],
  "setupScribes": [
    {
      "scFormat": "ScText",
      "scKind": "StdoutSK",
      "scName": "stdout",
      "scRotation": null
    }
  ]
}
